<a href="https://colab.research.google.com/github/Prashantthhh/23CSBTB39-40/blob/main/assignment2-part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import necessary libraries
import numpy as np
import pandas as pd

# Create lists
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]

# Identify their type
print("Type of list1:", type(list1))
print("Type of list2:", type(list2))

Type of list1: <class 'list'>
Type of list2: <class 'list'>


In [2]:
# Convert lists to NumPy arrays
array1 = np.array(list1)
array2 = np.array(list2)

# Identify their type
print("Type of array1:", type(array1))
print("Type of array2:", type(array2))

Type of array1: <class 'numpy.ndarray'>
Type of array2: <class 'numpy.ndarray'>


In [ ]:
# Perform operations
multiplication = array1 * array2
division = array1 / array2
poweroff = np.power(array1, 2)  # Square each element of array1

# Print results
print("Multiplication:\n", multiplication)
print("Division:\n", division)
print("Power of 2:\n", poweroff)

In [3]:
# Create a textual output
textual_output = f"Addition of Two:\n{array1} + {array2} = {array1 + array2}"

# Print the textual output
print(textual_output)

Addition of Two:
[1 2 3 4] + [5 6 7 8] = [ 6  8 10 12]


In [4]:
# Apply NumPy mathematical functions
sin_values = np.sin(array1)
log_values = np.log(array1)       # Natural logarithm
log2_values = np.log2(array1)     # Base-2 logarithm
exp_values = np.exp(array1)       # Exponential

# Print results
print("Sin values:\n", sin_values)
print("Log values:\n", log_values)
print("Log2 values:\n", log2_values)
print("Exp values:\n", exp_values)

Sin values:
 [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Log values:
 [0.         0.69314718 1.09861229 1.38629436]
Log2 values:
 [0.        1.        1.5849625 2.       ]
Exp values:
 [ 2.71828183  7.3890561  20.08553692 54.59815003]
